from collections import OrderedDict
from collections.abc import Callable, ItemsView, KeysView, Sequence
from typing import TYPE_CHECKING, Any, Protocol, Self, runtime_checkable

if TYPE_CHECKING:
    from bitstructures.base.bitstream import BitStream
    from bitstructures.base.codec import Codec, StackC, _Error, _Pass
    from bitstructures.base.objects import Container, EnumBase, Value

# ---- TYPING ----

type _Value = Any | EnumBase | BitStream | Container | Value
type ValueType = _Value | Sequence[ValueType]
type OrderedCollection[VT] = OrderedDict[str, VT]
type DefaultType = _Pass | _Error
type FunctType[T] = Callable[[Container], T]
type ExpType = Callable[[int], int]
# Can only take in ints, enumeration objects and raw bit streams
type WriteIoType = int | EnumBase | BitStream

# ---- PROTOCOLS ----


class SupportsSeek(Protocol):
    """Shadows the BitStream type classes."""

    def __len__(self) -> int: ...
    @property
    def bin(self) -> str: ...


class SupportsName(Protocol):
    @property
    def name(self) -> str: ...


@runtime_checkable
class SupportsPPrint(Protocol):
    def pprint(self) -> str: ...


class CodecProtocol(SupportsName, Protocol):
    def __init__(self, subcodec: "Codec | None" = None) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def size(self) -> int | FunctType[int]: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __rtruediv__(self, other: Any) -> Self: ...
    def _check_initialized(self) -> None: ...
    def _parse_io(self, raw: "bytes | BitStream") -> "BitStream": ...
    def _read_io(self, io: "BitStream", context: "Container", codecs: "StackC") -> "BitStream": ...
    def _write_io(
        self,
        io: "BitStream",
        context: "Container",
        codecs: "StackC",
        value: WriteIoType,
        size: int,
    ) -> None: ...
    def sizeof(self, io: "BitStream", context: "Container", codecs: "StackC") -> int: ...
    def io_parse(self, io: "BitStream", context: "Container", codecs: "StackC") -> None: ...
    def io_build(self, io: "BitStream", context: "Container", codecs: "StackC") -> None: ...


class StructProtocol(CodecProtocol, Protocol):
    @property
    def subcodecs(self) -> "StackC": ...
    def build(self, container: "Container") -> "BitStream": ...
    def parse(self, raw: "BitStream", *, readall: bool = True) -> "Container": ...


class AdapterProtocol(Protocol):
    def __init__(self, subcodec: "Codec") -> None: ...
    def io_parse(self, io: "BitStream", context: "Container", codecs: "StackC") -> None: ...
    def io_build(self, io: "BitStream", context: "Container", codecs: "StackC") -> None: ...
    def decode(self, context: "Container", value: Any) -> Any: ...
    def encode(self, context: "Container", value: Any) -> Any: ...


class SupportsKeysAndGetItem[KT: str, VT: Any](Protocol):
    def keys(self) -> KeysView[KT]: ...
    def items(self) -> ItemsView[KT, VT]: ...
    def __getitem__(self, key: KT, /) -> VT: ...
