name: pre-commit

on:
  pull_request:
  push:
    branches: [trunk]
    tags: []

jobs:
  PublishPackage:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
      - BuildPackage
      - CodeLinting
    steps:
        # Setup
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install UV
        uses: astral-sh/setup-uv@v7
        # Download Build
      - name: Download Build Dist
        uses: actions/download-artifact@v5
        with:
          name: build_artifacts
        # Publish Steps
      - name: Publish
        run: uv publish --dry-run
