name: Publish

on:
  push:
    tags:
      - 'v*'
      - '*.*.*'

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    environment:
      name: pypi

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Install UV
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
        with:
          python-version: "3.13"

      - name: Build Package
        run: uv build

      - name: Publish Package
        run: uv publish
